matrix-org/mjolnir

.gitignore
README.md
synapse_antispam/mjolnir/antispam.py

This would depend on matrix-org/synapse#6888 to be functional, it is likely worth taking a quick look at the API design in there first.
As noted in the synapse PR, I don't love the name of the chosen API method. Any suggestions would be appreciated!
I'm unsure if it makes sense to apply the same filtering (`is_user_banned`) over both the MXID and the display name, but it seemed like the simplest change to start with. What are your thoughts on this?
Related to matrix-org/synapse#5648.

Add an API to filter user directory searches by MXID or display name.

---

config/default.yaml
src/config.ts
src/protections/WordList.ts
src/protections/protections.ts

Add a protection for banning users based off of the use of certain blocked words.
Customization allows for modifying the word list in the config, using case-insensitive regexs to detect malicious messages.  Additionally, can be configured to only apply to messages set within a certain time period after a user joins, a feature which is beneficial in environments where certain words may come up naturally in conversation, but are almost always a red flag if used immediately on joining.  This does not add users to a ban list.
A feature like this stands to benefit many room admins.  In my experience, much of room administration is just noticing trolls and banning that quickly.  Many trolls make this blatantly easy by using inflammatory language immediately on joining, to the point that …

Add a WordList protection

---

config/default.yaml
src/commands/UnbanBanCommand.ts
src/config.ts

This adds a default enabled option to require confirmation for wildcard bans
(e.g. those containing `*` or `?`). Users will need to also add `--force` for
the commands to be accepted.

Add confirmation for wildcard bans

---

package.json
yarn.lock

There's a high severity CVE for y18n < 4.0.1. This should fix it.

Bumping dependency y18n

---

src/index.ts

Hey there,
I am currently in progress of creating a package/module of mjolnir for NixOS. While reviewing my PR we observed, that mjolnir does not set a non-zero exit code when encountering an error.
For example, when connecting to a not-yet-ready instance of pantalaimon or when connecting to an EMS hosted matrix server with missing consent: https://github.com/NixOS/nixpkgs/pull/123896#discussion_r651041787
e.g. for the missing consent case:
```
Jun 14 15:14:45 kif systemd[1]: Started mjolnir - a moderation tool for Matrix.
Jun 14 15:14:45 kif mjolnir[22947]: Mon, 14 Jun 2021 15:14:45 GMT [INFO] [index] Starting bot...
Jun 14 15:14:46 kif mjolnir[22947]: Mon, 14 Jun 2021 15:14:46 GMT [INFO] [index] Resolving protected rooms...
Jun 14 15:14:46 kif mjolnir[22947]: Mon, 14 Jun 2021 15:14:46 …
```

catch errors and set non-zero exit code

---

src/utils.ts

This is a deprecated API but the call to sync on an account in a large
number of rooms is taking too much time (and can fail), even with strict filtering
limiting the response to a single room.
This code is used to fetch the events to redact from a timeline,
so it is especially problematic.

Change use of a sync for obtaining the room history to a room initial sync.

---

src/protections/MessageIsMedia.ts
src/protections/protections.ts

* Simply redacts any media sent to the room, by anyone
* Meant to serve as a temporary measure to prevent gore image spam,
in conjunction with FirstMessageIsImage
TODOs:
* Add more fine grained handling, like
* Only redact media from new users
* Allow moderating / allowing media
* Run it by some sort of filter
* Filename filter
* Hostname / username filter
Endless possiblities, but this should do for now.
If the clients could totally disable media preview that would work too.

Add a new protection, MessageIsMedia

---

test/integration/mjolnirSetupUtils.ts

I assume this was the intention for this function, and doing this allows integration tests to use this function for other things

consistently use 'alias' in ensureAliasedRoomExists

---

src/Mjolnir.ts
src/models/BanList.ts
test/integration/banListTest.ts

Only shows changes to lists made by other accounts (than the one used by Mjolnir).
Displays when rules are added, removed and modified by either replacing the state event or redacting them.
Looks like this:

Provide notice showing how a BanList has changed after updating.

---

README.md

Master was renamed to main at some point, let's update the README to say so too.

README: Link to main instead of master

---

src/report/ReportManager.ts

As per feedback from users, since the labels are larger than the space on the buttons, it's hard to read.
With this patch, we keep the long text for the help and a single word for the button.

Abuse Report UX: Keep the text shorter

---

src/report/ReportManager.ts

We have gotten feedback that some homeservers are using more than one bot in the management room that Mjolnir is overreacting to. So in this patch we stop Mjolnir handling reactions to events the Mjolnir didn't send in the report manager.

Stop reacting to reports Mjolnir didn't send in report manager.

---

config/harness.yaml
mx-tester.yml
test/integration/clientHelper.ts
test/integration/mjolnirSetupUtils.ts

- Use the configured username & password when registering the test user to run Mjolnir with (was hardcoded).
- Remove bogus imports from the helper that have accidentally been introduced with VSCode.
- Keep `enable_registration: true` in the homeserver config to save time.

Improvements to manual testing with the test:manual script.

---

src/LogProxy.ts
src/utils.ts
test/integration/utilsTest.ts

if `roomIds` has duplicates in it, the replacements on L196 and L198 will break the previous replacements.
example:
```
!asd:matrix.org
```
becomes
```
<a href=\"https://matrix.to/#/!asd:matrix.org?via=matrix.org\">!asd:matrix.org</a>
```
becomes
```
<a href=\"https://matrix.to/#/<a href=\"https://matrix.to/#/!asd:matrix.org?via=matrix.org\">!asd:matrix.org</a>?via=matrix.org\"><a href=\"https://matrix.to/#/!asd:matrix.org?via=matrix.org\">!asd:matrix.org</a></a>
```
et cetera

make `roomIds` param on replaceRoomIdsWithPills a Set<string>

---

synapse_antispam/mjolnir/list_rule.py

Or it'll just ignore 1.3.1 rules.

Update legacy antispam plugin with newer types.

---

config/default.yaml

It isn't clear what it means to have the server "struggle" with state requests.
This change is trying to make the configuration more actionable to end users.

default.yaml: expand on fasterMembershipChecks

---

src/Mjolnir.ts
src/commands/ProtectionsCommands.ts
src/protections/BasicFlooding.ts
src/protections/FirstMessageIsImage.ts
src/protections/IProtection.ts
src/protections/MessageIsMedia.ts
src/protections/MessageIsVoice.ts
src/protections/WordList.ts
src/protections/protections.ts
test/integration/protectionSettingsTest.ts

rebase on #158
primary win of this is dynamism (by not relying on `PROTECTIONS`), which also allows us to mock protections for integration tests, but it's also generally a lot cleaner

refactor (and simplify) how protections are stored in-memory

---

synapse_antispam/mjolnir/antispam.py
synapse_antispam/mjolnir/ban_list.py

The general rule is: `synapse.module_api` is OK, but anywhere else is not.
Luckily the other two things are already exported for public use. We don't guarantee the stability/existence of functions in other parts of the code.
Related: #173, #174.

Use public Synapse imports for `UserID` and `run_as_background_process`

---

src/webapis/WebAPIs.ts

In a general use case practice the frontend web services should be agnostical of the required CORS settings as they should be specified by the backend applications directly. And in case they should just rewrite the backend provided headers appropriately and not arbitrarily add 'em on its behalf.

Set missing CORS headers for Report API responses.

---

src/utils.ts

This should cut a lot on the noise in logs.

Reduce stackspam

---

synapse_antispam/mjolnir/antispam.py

https://github.com/matrix-org/mjolnir/issues/245

Fix incorrect type declaration in check_username_for_spam

---

synapse_antispam/mjolnir/antispam.py

Fixes #244.
We've made the same (unfortunate) mistake before in https://github.com/matrix-org/message_limit/commit/a6e4709a843daa30cce5f7a1c7d1dbc96753d221; see also https://github.com/matrix-org/synapse/commit/73fc4887834b33afaf23ff48a68772f8ef9b924c.

Fix block_usernames config option

---

.github/workflows/docker-hub-latest.yml
.github/workflows/docker-hub-release.yml

Currently the `latest` tag on dockerhub is out of sync as it was using docker hub's autobuild which matrix.org no longer supports. 
Here we use github actions to push and tag the images instead.

Use github workflows to push dockerhub images+tags.

---

src/Mjolnir.ts
src/index.ts

There is no reason to call process.exit() from `index.ts` or in `Mjolnir.start()` because
https://nodejs.org/api/process.html#warning-using-uncaughtexception-correctly
>The 'uncaughtException' event is emitted when an uncaught JavaScript exception bubbles all the way back to the event loop. By default, Node.js handles such exceptions by printing the stack trace to stderr and exiting with code 1, overriding any previously set process.exitCode. Adding a handler for the 'uncaughtException' event overrides this default behaviour.

Make startup failures more controlled and understandable.

---

README.md

Using the example as is will cause Synapse to not start with the following traceback:
```
Apr  3 09:52:37 akademeia matrix-synapse-worker_media_1[2922268]: 2022-04-03 09:52:37,038 - synapse.app._base - 242 - CRITICAL - sentinel - Error during startup
Apr  3 09:52:37 akademeia matrix-synapse-worker_media_1[2922268]: Traceback (most recent call last):
Apr  3 09:52:37 akademeia matrix-synapse-worker_media_1[2922268]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/_base.py", line 227, in wrapper
Apr  3 09:52:37 akademeia matrix-synapse-worker_media_1[2922268]:     await cb(*args, **kwargs)
Apr  3 09:52:37 akademeia matrix-synapse-worker_media_1[2922268]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/_base.py", line 438, in start
Apr  3 …
```

Amend README.md for antispam config example.

---

mx-tester.yml

We use this both in tests and for ease of manual testing.

Synapse requires registration to be explicit

---

package.json
synapse_antispam/setup.py

The reason we want this is so that people do not forget to change the verison number in the synapse module.
The precedent is that the version number has been 0.1.0 since the begging until now.
While this solution does mean that there may be new version of the module where
nothing has actually changed, this is still better than not changing the version at all.
Another version scheme for the module would be inconsistent to
the git repository tags and that has the potential to cause much more confusion
than "blank" version bumps.
If this is a problem, then antispam must be extracted to another repository.
In order to test this, run `yarn version --patch` observe the changes with `git log` and `git diff HEAD~`,
then YOU MUST delete the tag with `git tag --delete vd.d.d` when you are finished. …

Change antispam Python module verison with mjolnir version.

---

package.json
test/integration/commands/makedminCommandTest.ts
test/integration/roomMembersTest.ts
test/integration/standardConsequenceTest.ts
yarn.lock

Fixes https://github.com/matrix-org/mjolnir/issues/281
`ts-mocha` has also been updated to make running locally possible (else it gives a confusing error that `tsconfig.json` is not "json" or the likes)

Add some `preset: public_chat` / user invites in tests (to fix CI)

---

src/Mjolnir.ts
src/protections/IProtection.ts
src/protections/JoinWaveShortCircuit.ts
src/protections/protections.ts

This partially addresses https://github.com/matrix-org/mjolnir/issues/267
This adds `JoinWaveShortCircuit`, a protection which will set the room to invite-only as soon as X amount of users (default 50) join the room in the last X minutes (default 60).
The protection works with a Bucket, starting the bucket at first join, and only counting users if its been X minutes since the last bucket start.
(The reasoning for this particular approach is likely sensitive (in relation to other protections), so please reach out if you'd like to hear it.)
It has two settings; 
- `maxPer`, which determines how many users will have to join in the last X minutes before it will trigger the protection.
- `timescaleMinutes`, the timescale in X minutes, this determines on what time scale the bot will look at …

Add Join Wave Short-Circuit Protection

---

.gitignore
src/Mjolnir.ts
src/protections/IProtection.ts
src/report/ReportManager.ts

The callback function at https://github.com/matrix-org/mjolnir/blob/main/src/Mjolnir.ts#L1026 receives the event packed object as single argument and not all the arguments 'emselves. Also to avoid any possible scope issues it's best to pass the Mjolnir object itself to the CB.

Fix traceback on Abuse Report.

---

src/commands/CommandHandler.ts
src/commands/KickCommand.ts

This pull requests adds for glob support in the `!mjolnir kick` command.
```
!mjolnir kick @*:domain.tld <reason> --force
```
This command will kick every user having a mxid matching `domain.tld`.  
You can also still kick a particular user:
```
!mjolnir kick @user:domain.tld <reason>
```
Tested on the Furry Tech room (`vRGLvqJYlFvzpThbxI:matrix.org`) after a spam wave.  
It kicked over 13k bots in a matter of hours without putting too much strain on the homeserver.  
For instance, this command was matching `@spam*`:
Signed-off-by: Jae Lo Presti <me@jae.fi>

Glob kick command

---

test/integration/reportPollingTest.ts

So the test before sometimes sent the report *before*
the protection (that is used to check whether we have received
the report) was registered.
This of course meant that we didn't ever receive the report from
the perspectivee of the test.
This PR should now mean we always send the report after
registering the protection.

Report polling test temporality

---

package.json
src/utils.ts
test/integration/banListTest.ts
test/integration/throttleTest.ts

This is really terrible and has meant whenever anyone has run `yarn test:integration` they have only been running this test.
💀💀💀
Edit: So it turned out a couple of tests (ban list test & the throttling test) were silently broken because of the issue this PR originally fixes, so these tests have also been fixed as a part of this PR

Remove debug leftovers from a test.

---

src/models/ListRule.ts

They have been in the spec for ~3 years now and most mjolnirs should be
able to handle them. Let's use the stable endpoint now, so that other
moderation tools don't need to implement the legacy identifier to handle
new bans at some point.
Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>

Use stable prefixes for policy recommendations

---

tsconfig.json

Node16+ allows usage of ES2021 features, and frankly ES2015 is very old now.

Update tsconfig.json touse ES2021

---

src/Mjolnir.ts
src/commands/ImportCommand.ts
src/commands/UnbanBanCommand.ts
src/models/ListRule.ts
src/models/PolicyList.ts
test/integration/banListTest.ts

1. We keep track of the event that created a list rule so that we
can remove the rule by having a way to determine the original state key for the rule.
This is because the state key of rules can be anything and should not be
relied on by Mjolnir to unban things (which it was doing).
2. The old scheme for producing a state key was causing for some entities to escape bans
https://github.com/matrix-org/mjolnir/issues/322.
We could have used a hash or something similar, but we know that
the reason for the `rule:${entity}` scheme existed was for ease of debugging
and finding rules in devtools. So instead we have followed a scheme simalar to
bridges where the first character of an mxid is replaced with an underscore.
Everything else just gets put into the state key. Since domains can't have '@' …

Rework the banning and unbanning of entities in PolicyLists.

---

src/commands/StatusCommand.ts

This is a partial fix for #75. I'd add the readonly status too, but I don't think Mjolnir tracks that.

Add list shortcodes to status command output

---

src/commands/CommandHandler.ts

**There's an annoying typo that's been bugging me long enough to make a PR:**
`!mjolnir config set <protection>.<setting> [value]                  - Change a projection setting`

Fix typo in bot command response

---

.github/workflows/mjolnir.yml

mx-tester takes several minutes to install and that's a shame. Let's see if we can cache it across runs.

CI: Let's try and cache mx-tester installs

---

README.md
test/integration/abuseReportTest.ts
test/integration/fixtures.ts
test/nginx.conf

In both our instructions and our tests, we use the r0 endpoint to intercept abuse reports. This endpoint is deprecated and not implemented by all clients. This PR updates the instructions and tests to the new endpoint.

Update tests and instructions to intercept reports also with v3 endpoint

---

src/ProtectedRooms.ts
src/models/AccessControlUnit.ts
src/models/ListRule.ts
src/models/PolicyList.ts
test/integration/banListTest.ts

This PR creates a new model called an AccessControlUnit.
The ACL unit allows you to combine an policy lists and conveniently test users and servers against them.
The main motivation for this work is provide access control on who can provision and continue to use mjolnir instances in the appservice component.
We include a new recommendation type `org.matrix.mjolnir.allow` which can be used with user and server entity types to create allow lists.
We have also replaced the destructing of policy lists in `applyServerACL` and `applyMemberBans` (in `ProtectedRooms.ts`) with calls to the AccessControlUnit. 
Adding commands to add/remove allowed entities is not something i want to do at the moment.

Access Control

---

src/commands/CreateBanListCommand.ts
src/models/PolicyList.ts
test/integration/banListTest.ts

https://github.com/matrix-org/matrix-spec-proposals/pull/3784
This was extracted from the appservice mjolnir work to reduce review burden.
The idea behind supporting MSC3784 is that clients can start to provide UX for editing policy lists directly rather than going through Mjolinr commands.

Refactor list creation with MSC3784 support.

---

package.json
src/Mjolnir.ts
src/ProtectedRoomsConfig.ts
src/ProtectedRoomsSet.ts
src/commands/CreateBanListCommand.ts
src/commands/ListProtectedRoomsCommand.ts
src/commands/StatusCommand.ts
test/integration/protectedRoomsConfigTest.ts
test/integration/roomMembersTest.ts
yarn.lock

Closes https://github.com/matrix-org/mjolnir/issues/370
Covers all of the points we wanted to refactor on in #370 too.
This PR factors out the management of `explicitlyProtectedRoomIds` into a `ProtectedRoomsConfig` class which also manages persisting the list to account data.
It then nukes `protectedJoinedRoomIds`, `unprotectedWatchedListRooms` and `explicitlyProtectedRoomIds` from Mjolnir. 
If `config.protectAllJoinedRooms` is true, rather than tracking which policy lists should not be protected based on the create event of the list (which is what `unprotectedWatchedListRooms` was for), we instead require that lists be explicitly protected. This will already be the case if the list was created with Mjolnir.
To make sure it is obvious that a list is unprotected, the status command will …

fix `config.protectAllJoinedRooms` leaking into explicitly protected rooms

---

src/Mjolnir.ts

`Mjolnir.resyncAllJoinedRooms` needs policy lists to be loaded into mjolnir in order to filter them out of the protect rooms set (unless explicitly protected). This is so that you don't end up having mjolnir complain about protecting a list which you have no control over, and are just watching (e.g. #matrix-org-coc-bl:matrix.org).
https://matrix.to/#/!WpbOWAblxueZXAAnjj:matrix.org/$f0rKGBOJTcaC_bLPfydApg8oUEw4caZNk-9G1Sa4QSU?via=matrix.org&via=envs.net&via=element.io

Stop Mjolnir blindly protecting all policy lists at startup.

---

docs/setup_docker.md
docs/setup_selfbuild.md
package.json
src/config.ts
yarn.lock

This is what was used prior to https://github.com/matrix-org/mjolnir/pull/347.
It was a nice idea motivated to drop a dependency that was confusing.
It was just never followed through and was underestimated how much disruption it would cause.
It was also believed that the library would mean there could only ever be one global copy of the config,
It was followed up by:
https://github.com/matrix-org/mjolnir/pull/369
https://github.com/matrix-org/mjolnir/pull/357
https://github.com/matrix-org/mjolnir/pull/429
https://github.com/matrix-org/mjolnir/pull/397
https://github.com/matrix-org/mjolnir/issues/365
For simplicity sake I am reinstating the library.
The practice of loading default.yaml by default is also dangerous
and has led to issues multiple times in #mjolnir:matrix.org.
It is a sample …

Config fixes

---

config/default.yaml
package.json
src/ManagementRoomOutput.ts
src/Mjolnir.ts
src/config.ts
src/index.ts
src/utils.ts
test/integration/mjolnirSetupUtils.ts
yarn.lock

The Sentry package is very useful for monitoring runtime errors. With this PR, we simply add the necessary mechanism to:
- log to sentry any uncaught error that reaches the toplevel, including startup errors;
- log to sentry any error that we already log internally as `ERROR`.
This also introduces support for monitoring performance with Sentry. That feature will require further instrumentation.

Very basic support for Sentry.

---

src/Mjolnir.ts
src/ProtectedRoomsSet.ts
src/models/PolicyList.ts

For some reason we were relying on a mjolnir listening to `'PolicyList.batch'` to update policy lists.
This was exposing an implementation detail to Mjolnir and including it as part of the implementation of
`PolicyList.updateForEvent()` which is supposed to cause the `PolicyList` to update (eventually).
I am confident this was because of a need before batching was introduced to get the changes to a policy list directly from the method call to `PolicyList.update()`, whereas now you can just listen to `PolicyList.update`.
The `'PolicyList.batch'` event has now been removed and the PolicyList event batcher (`UpdateBatcher`) now calls `PolicyList.update()` internally.

Make `updateForEvent` actually update PolicyLists.

---

src/Mjolnir.ts
src/config.ts

Also assert that we if `autojoinOnlyIfManager` is enabled that
the user has provided a space for `acceptInvitesFromSpace`.
It does sound like `autojoinOnlyIfManager` would imply that
anyone could send an invitation to the mjolnir if
`autojoinOnlyIfManager` is false.
This has never been the case though, and it is not sensible
either, especially if `protectAllJoinedRooms` is also true.
Additionally the documentation in `config/default.yaml`
has always claimed that `autojoinOnlyIfManager` is "true by default".
This setting has confused users in #mjolnir:matrix.org before
Closes https://github.com/matrix-org/mjolnir/issues/436.
Also fixes an issue in the appservice where we require
`autojoinOnlyIfManager` to always be explicitly set to false
or it crashes any Mjolnir receiving an invite.

Make `autojoinOnlyIfManager` true by default.

---

config/harness.yaml
package.json
src/Mjolnir.ts
src/appservice/AppService.ts
src/appservice/cli.ts
src/appservice/config/config.ts
src/config.ts
src/index.ts
src/utils.ts
src/webapis/OpenMetrics.ts
src/webapis/WebAPIs.ts
test/integration/fixtures.ts
test/integration/mjolnirSetupUtils.ts
test/integration/openMetricsTest.ts
tsconfig.json

This PR:
- creates an OpenMetrics server that enables collecting performance data from this process by e.g. a Prometheus server;
- exposes as metrics the performance and success/failures of http requests with MatrixBot;
- exposes as metrics system performance (e.g. CPU usage, memory usage).
Further metrics may of course be added.

Basic support for OpenMetrics (aka Prometheus)

---

mx-tester.yml
src/Mjolnir.ts
src/ProtectedRoomsSet.ts
src/appservice/Api.ts
src/appservice/AppService.ts
src/appservice/MjolnirManager.ts
src/appservice/config/config.example.yaml
src/appservice/config/config.harness.yaml
src/appservice/config/config.ts
src/commands/CommandHandler.ts
src/commands/SetupDecentralizedReportingCommand.ts
src/config.ts
src/protections/IProtection.ts
src/protections/LocalAbuseReports.ts
src/protections/ProtectionManager.ts
src/report/ReportManager.ts
test/integration/abuseReportTest.ts
test/integration/moderationRequestTest.ts
test/integration/protectionSettingsTest.ts
test/integration/reportPollingTest.ts
test/integration/standardConsequenceTest.ts

Traditionally, when a user clicks "report" in a Matrix client, this goes to the homeserver administrator, who often is the wrong person for the job.
MSC3215 introduces a mechanism to let clients cooperate with a bot to send the report to the moderator instead. Client support has landed in Element Web (behind a Labs flag) in in 2021. This allows Mjölnir to serve as the partner bot.

A first implementation of report-to-moderator

---

src/protections/MessageIsMedia.ts

Currently, you can circumvent blocks on media using stickers. Since sticker messages basically allow you to embed an arbitrary image, they have almost equivalent functionality to images, and should count as media to be blocked as well.
Credit to @eyjhb for successfully hacking together a custom event showing cat pictures to demonstrate.

Detect stickers as media

---

releasing.md

Per the comment at https://github.com/matrix-org/mjolnir/pull/500#discussion_r1402528806, there is a script for releasing and prior instructions from the wiki. I've added the relevant bits from that here.

Update releasing instructions to use script

---

mx-tester.yml
src/Mjolnir.ts
src/commands/CommandHandler.ts
src/commands/SuspendCommand.ts
src/commands/UnsuspendCommand.ts
src/commands/unSuspendCommand.ts
test/integration/commands/suspendCommandTest.ts

As the title states - note that these commands will not work if the homeserver does not have the experimental feature `msc3823_account_suspension` enabled.

Add commands to suspend/unsuspend user

---

src/models/PolicyList.ts

In some cases the matrix.to url provided to the policy list is just a room alias that's been converted to the matrix.to url format. If that's the case, make sure we resolve the alias in a way that captures the via servers before trying to join the room. 
Fixes #503

Check for via servers before trying to join room in policy list manager

---

src/commands/DeactivateCommand.ts
src/commands/KickCommand.ts
src/commands/SetPowerLevelCommand.ts
src/commands/ShutdownRoomCommand.ts
src/commands/UnbanBanCommand.ts
src/utils.ts
synapse_antispam/mjolnir/list_rule.py

Use modern language

---

src/utils.ts

Self explanative, do not interrupt the loop and just carry on with the remaining entries in the queue.

Do not interrupt redact sequences because of exceptions on backfilling

---

CONTRIBUTING.md

The Matrix.org Foundation is rolling out this updated DCO across all public repositories in its namespace. Of note, this DCO does not require the use of "real" or "legally identifiable" names.

remove real name requirement from DCO

---

src/protections/MessageIsMedia.ts
test/integration/protectionSettingsTest.ts

As the title states.
Fixes #481

Enhance media protections

---

src/models/PolicyList.ts

Resolves #404. Resolves aliases and gets any via servers before storing in watch list (note that this builds on #514).

Resolve aliases and get via servers before storing watch list

---

src/protections/NsfwProtection.ts

This means that the error handler will actually fire on failed redaction.

Fix NSFW protection not awaiting redaction

---

src/protections/MentionSpam.ts
src/protections/ProtectionManager.ts
test/integration/mentionSpamProtectionTest.ts

Fixes #309 #211 
This protection checks whether a message contains a large number of mentions and redacts the message. It currently checks the mentions array, then the body and finally the formatted body. I've chosen 10 as a sensible max number of mentions before the message may be considered spam, although this is configurable via a setting.

Add protection for mention spam

---

src/protections/NsfwProtection.ts
test/integration/banListTest.ts

- better error messages from nsfwProtection
- fix a flaky test

A few small fixes

---

package.json
src/protections/MentionSpam.ts
test/integration/mentionSpamProtectionTest.ts
yarn.lock

Extend mention spam protection to handle displayname mentions. 
All credit to half-shot

Add displayname mention spam protection

---

test/integration/messageIsMediaProtectionTest.ts

Add a test verifying messageIsMediaProtection

---

config/default.yaml
src/Mjolnir.ts
src/config.ts
test/integration/forwardedMentionsTest.ts
test/integration/protectedRoomsConfigTest.ts
test/integration/standardConsequenceTest.ts

Fixes https://github.com/matrix-org/mjolnir/issues/89
This works by checking to see if the bot has been mentioned in any of the protected rooms when a message comes in, and then will ignore any future mentions for the next 8 minutes (giving administrators a chance to deal with the offense, and to reduce spam). 
This is off-by-default, as it's enough of a behaviour change that I think administrators should opt into this explicitly.

Notify moderation room when users in protected rooms mention the bot (configurable)

---

src/Mjolnir.ts
test/integration/commands/UnbanBanTest.ts

this surfaced two bugs, one somewhat related and one not - one causing bans being synced from the policy list to not be sent to protected rooms, and one preventing read receipts from being sent properly. Both are fixed in the second commit.

Add a test verifying `unban` command 

---

src/commands/CommandHandler.ts

while I was in the area, make the help menu a little more manageable by grouping related commands. I couldn't fit all of the new menu into a screenshot, but the gist of it is:
Areas are:
- Protection Actions/Options
- Moderation Actions
- Policy List Options/Actions
- Room Managment
- Bot Status and Management
Fixes #204 and #52

Stop printing help menu on unknown command

---

src/ManagementRoomOutput.ts
src/ProtectedRoomsSet.ts
src/commands/KickCommand.ts
src/commands/SuspendCommand.ts
src/protections/BasicFlooding.ts
src/protections/FirstMessageIsImage.ts
src/utils.ts

Use spoilers when mentioning targets of a rule

---

test/integration/commands/suspendCommandTest.ts
test/integration/dontBanSelfTest.ts

Looking through a few days worth of test failures it seems to be mostly the suspension test - notably https://github.com/matrix-org/mjolnir/pull/568/commits/d3e5a2e7496076b14b15865538469b4572bfb68c should help as well, I think these are the two most consistent failures.
We can fix more as the signal gets clearer for more inconsistent flakes once these are fixed.

Unflake tests

---

package.json
src/protections/MentionSpam.ts
test/integration/mentionSpamProtectionTest.ts
yarn.lock

This reverts commit c7060681ec45927aac9330abca8d2e36409ac4ed.

Revert "Add displayname mention spam protection (#537)"

---

src/protections/NsfwProtection.ts

For the size of a standard matrix event, it's not worth doing two matches for `mxc` here.

Support scanning stickers for NSFW content, and don't error so loudly when a MXC is missing

---

src/protections/NsfwProtection.ts

This PR adds the ability to skip NSFW processing if the sensitivity is set to 0.0.
This saves resources, and makes redactions happen faster, allowing it to be used as a generic "disallow images" protection.
I wonder if a setting to opt out of this behavior should be included, even though one could set the sensitivity to 0.0002 to opt out?

Skip NSFW classification if treshold is 0.0
