matrix-org/mjolnir

README.md, synapse_antispam/mjolnir/__init__.py, synapse_antispam/mjolnir/antispam.py, synapse_antispam/mjolnir/ban_list.py, synapse_antispam/mjolnir/list_rule.py, synapse_antispam/setup.py
This is looking for general code review rather than linting. Specifically, is this something that the backend team would be happy to run on matrix.org and is it valid enough Python?
**Requires https://github.com/matrix-org/synapse/pull/6259**
=> Add Synapse antispam module

synapse_antispam/mjolnir/antispam.py
One thing to note is, that this PR doesn't support room alias rules, since no room alias resolution is performed.
Signed-off-by: Randshot <randshot@norealm.xyz>
=> Add room rule check to invites

src/commands/UnbanBanCommand.ts
This PR fixes the `!mjolnir unban` command, so that unbans are properly applied when supplying the `apply` argument as `true`.
Signed-off-by: Randshot <randshot@norealm.xyz>
Fixes https://github.com/matrix-org/mjolnir/issues/22
=> Fix unban command

src/commands/UnbanBanCommand.ts, test/commands/UnbanBanCommandTest.ts
This improves the force argument parsing to keep it from getting glued onto the
reason. It also adjusts tests for the new behaviour.
=> Improve force handling

src/Mjolnir.ts
Fixes https://github.com/matrix-org/mjolnir/issues/83
Signed-off-by: Neil Middleton <neilm@element.io>
=> Make `!mjolnir` not case sensitive

Dockerfile, README.md, package.json
Needed to merge https://github.com/matrix-org/mjolnir/pull/186 & node 12 is approaching EOL.
=> Bump minimum node version to 14

package.json, src/ErrorCache.ts, src/LogProxy.ts, src/Mjolnir.ts, src/commands/AliasCommands.ts, src/commands/CommandHandler.ts, src/commands/CreateBanListCommand.ts, src/commands/DumpRulesCommand.ts, src/commands/ProtectionsCommands.ts, src/commands/UnbanBanCommand.ts, src/models/BanList.ts, src/protections/BasicFlooding.ts, src/protections/ProtectionSettings.ts, src/report/ReportManager.ts, src/utils.ts, src/webapis/WebAPIs.ts, tsconfig.json
~~still one more issue left to fix, with `express`~~ guess not!
=> enable noImplicitAny

src/Mjolnir.ts, src/protections/IProtection.ts, src/protections/ProtectionSettings.ts, src/protections/TrustedReporters.ts, src/protections/protections.ts, src/report/ReportManager.ts, src/webapis/WebAPIs.ts
~~I feel like moving the report callback in to Mjolnir from ReportManager might not be the best move~~
=> trusted reporters

src/commands/UnbanBanCommand.ts, src/models/BanList.ts, test/integration/banListTest.ts
Fixes https://github.com/matrix-org/mjolnir/issues/220
=> Remove old rules when unbanning entities from BanLists.

src/commands/ShutdownRoomCommand.ts, test/integration/commands/shutdownCommandTest.ts
=> send whole channel shutdown reason, not just the first word

package.json, src/Mjolnir.ts, src/RoomMembers.ts, src/commands/StatusCommand.ts, src/protections/protections.ts, test/integration/commands/commandUtils.ts, test/integration/roomMembersTest.ts, yarn.lock
This should be useful during spam attacks.
=> A command to show when users in a given room have joined

package.json, src/Mjolnir.ts, src/commands/CommandHandler.ts, src/commands/KickCommand.ts, src/commands/SinceCommand.ts, src/commands/StatusCommand.ts, src/utils.ts, test/integration/commands/commandUtils.ts, test/integration/roomMembersTest.ts, tsconfig.json, yarn.lock
This command should help in case a room is besieged by bots.
This PR builds upon https://github.com/matrix-org/mjolnir/pull/225 , so that PR should be reviewed/merged first.
=> New command `!mjolnir since <date or duration> <kick | ban | show> <limit> [reason] [...rooms]`

mx-tester.yml, src/Mjolnir.ts, src/queues/ProtectedRoomActivityTracker.ts, src/queues/RoomActivityTracker.ts, test/integration/banListTest.ts, tsconfig.json
https://github.com/matrix-org/mjolnir/issues/273
https://github.com/matrix-org/mjolnir/pull/164
=> Apply members and server bans to the most recently active rooms first.

.gitignore, src/Mjolnir.ts, src/protections/IProtection.ts
Reverts matrix-org/mjolnir#230
This seems to break stuff https://github.com/maranda/mjolnir/runs/6423583907?check_suite_focus=true
=> Revert "Fix traceback on Abuse Report."

config/default.yaml, src/Mjolnir.ts, src/commands/KickCommand.ts, src/config.ts, src/queues/ThrottlingQueue.ts, test/integration/throttleQueueTest.ts
Is this the kind of thing you had in mind, @Gnuxie ?
=> A background queue for kicking

package.json, test/integration/roomMembersTest.ts, yarn.lock
Also, a few changes that should make the test slightly more readable.
=> Fix: roomMemberTest off-by-one error

package.json, test/integration/roomMembersTest.ts, yarn.lock
Reverts matrix-org/mjolnir#319
Oops, unrelated changes made it into the PR.
=> Revert "Fix: roomMemberTest off-by-one error"

yarn.lock
```
npm install --package-lock-only
npm audit fix
rm yarn.lock
yarn import
```
```
npm audit
json-schema  <0.4.0
Severity: critical
json-schema is vulnerable to Prototype Pollution - https://github.com/advisories/GHSA-896r-f27r-55mw
fix available via `npm audit fix`
node_modules/json-schema
jsprim  0.3.0 - 1.4.1 || 2.0.0 - 2.0.1
Depends on vulnerable versions of json-schema
node_modules/jsprim
minimist  <1.2.6
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/minimist
nanoid  3.0.0 - 3.1.30
Severity: moderate
Exposure of Sensitive Information to an Unauthorized Actor in nanoid - https://github.com/advisories/GHSA-qrpm-p2h7-hrv2
fix available via `npm audit fix`
node_modules/nanoid …
```
=> Audit yarn.lock and then audit the packages.

test/integration/banListTest.ts, test/integration/roomMembersTest.ts
If you add `"no-floating-promises": true` it's very easy
to find where this is done accidentally.
Not sure we can keep that on all the time yet though..
=> Missing awaits on floating promises in tests.

src/ProtectedRoomsSet.ts
https://github.com/matrix-org/mjolnir/issues/392.
=> Always echo policy list changes

src/commands/UnbanBanCommand.ts, src/queues/UnlistedUserRedactionQueue.ts
Also fix a years long bug where the Flooding/Media protection wouldn't stop redacting users
Closes https://github.com/matrix-org/mjolnir/issues/393
Closes https://github.com/matrix-org/mjolnir/issues/394
=> Improve the clarity of the unban command

src/protections/WordList.ts
Made several improvements to catch edge cases.
=> WordList was matching everything.

docs/moderators.md
=> docs: fix small typo in `moderators.md`

src/appservice/AppService.ts, test/appservice/integration/provisionTest.ts, test/appservice/integration/webAPITest.ts, test/appservice/utils/harness.ts, test/appservice/utils/webAPIClient.ts, tsconfig.json
Some minor fixes now that they have been.
=> Appservice tests weren't added to tsconfig.json properly.

src/commands/ProtectionsCommands.ts
=> fix 2 issues in `!config get`

package.json
=> Bump package version in preparation for release

src/index.ts
=> Support non-password based login

src/utils.ts, test/integration/commands/redactCommandTest.ts
=> Fix call to admin redaction api 
